"""
Community-feed YAML exporter.

Emits a ``community-submission.yaml`` template shaped after the
``aptwatch/community/TEMPLATE.yaml`` pattern. The file is machine output
(there is a ``DO NOT EDIT`` banner prepended on write) that a human
reviewer later hand-tunes before submission.

Design rules:

- Every ``submission`` field is required. Missing ``campaign_tag`` or
  ``submitter`` raises :class:`IOCExportError` before any file is written.
- ``indicators`` are emitted one per input IOC, preserving input order.
  Confidence is bucketed into ``low`` / ``medium`` / ``high`` so the
  downstream feed format doesn't need to know our numeric scale.
- ``findings`` may be empty — the community format is still valid with
  pure IOC submissions — but we always emit the key so the shape is
  stable.

References:

- docs/design/analysis-output-pipeline.md
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from core.analysis.export_stix import IOCExportError
from core.types import Finding, IOCVerdict, utcnow

# Banner prepended verbatim to the written file. YAML parsers skip
# leading comments so the file round-trips cleanly.
_BANNER = (
    "# DO NOT EDIT - generated by APTWatcher analyze\n"
    "# Hand-review and adjust before submitting to a community feed.\n"
)


def _confidence_bucket(score: float | None) -> str:
    """Map a 0.0-1.0 score to the community-feed low/medium/high scale."""
    if score is None:
        return "low"
    if score >= 0.75:
        return "high"
    if score >= 0.4:
        return "medium"
    return "low"


def _iso(dt: Any) -> str | None:
    if dt is None:
        return None
    # pydantic hands us real datetimes; guard for strings just in case.
    if hasattr(dt, "isoformat"):
        iso: str = dt.isoformat()
        return iso
    return str(dt)


def _indicator_entry(ioc: IOCVerdict) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "type": ioc.ioc_type,
        "value": ioc.value,
        "confidence": _confidence_bucket(ioc.confidence),
        "source": "APTWatcher",
    }
    first_seen = _iso(ioc.first_seen)
    if first_seen is not None:
        entry["first_seen"] = first_seen
    last_seen = _iso(ioc.last_seen)
    if last_seen is not None:
        entry["last_seen"] = last_seen
    return entry


def _finding_entry(finding: Finding) -> dict[str, Any]:
    return {
        "id": finding.finding_id,
        "title": finding.summary,
        "confidence": finding.confidence,
        "techniques": list(finding.mitre),
    }


def export_community_yaml(
    *,
    iocs: list[IOCVerdict],
    findings: list[Finding],
    output_path: Path,
    campaign_tag: str,
    submitter: str,
) -> dict[str, Any]:
    """Emit a community-feed-style YAML template to ``output_path``.

    Returns the in-memory document the exporter serialized, for callers
    that want to hash it or hand it to a publication adapter.
    """
    if not campaign_tag:
        raise IOCExportError("campaign_tag is required")
    if not submitter:
        raise IOCExportError("submitter is required")
    if not iocs and not findings:
        raise IOCExportError(
            "community submission requires at least one IOC or finding"
        )

    document: dict[str, Any] = {
        "submission": {
            "campaign": campaign_tag,
            "submitter": submitter,
            "submitted_at": utcnow().isoformat(),
        },
        "indicators": [_indicator_entry(ioc) for ioc in iocs],
        "findings": [_finding_entry(f) for f in findings],
    }

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(document, sort_keys=False, allow_unicode=True)
    output_path.write_text(_BANNER + body, encoding="utf-8")
    return document


__all__ = [
    "export_community_yaml",
]
