"""
APTWatcher -- shared brain.

This package is the single source of logic used by every deployment mode:

- Mode A (Direct Agent Extension): CLI imports from `core`.
- Mode B (MCP Server): server tools are thin wrappers over `core`.
- Mode C (Hybrid): both of the above.

Nothing in `core` should know which deployment mode is invoking it. If a
function needs mode-specific behavior, that indicates it belongs in a
surface module (`agent_extension`, `mcp_server`) instead.

References:
- docs/architecture/shared-brain.md
- docs/architecture/README.md
"""

from __future__ import annotations

__version__ = "0.1.0a0"

from core.agent_loop import (
    AgentLoop,
    AgentState,
    ExecutionRecord,
    PlanStep,
    ReportEmitError,
    SelfCorrectionDecision,
    VerificationIssue,
)
from core.analysis import (
    RuleGenerationError,
    SigmaRule,
    SuricataRule,
    YaraRule,
    generate_sigma_rules,
    generate_suricata_rules,
    generate_yara_rules,
)
from core.analysis.export_community import export_community_yaml
from core.analysis.export_iocs_txt import export_per_type_txt
from core.analysis.export_stix import IOCExportError, export_stix_bundle
from core.analysis.report_docx import ReportRenderError, render_docx_report
from core.analysis.report_markdown import (
    render_analyst_markdown,
    render_ttp_assessment,
)
from core.analysis.report_stats import render_generation_report
from core.audit import AuditLogger
from core.bundle import (
    BundleManifest,
    BundleSignatureError,
    IncidentBundle,
    export_bundle,
    generate_keypair,
    import_bundle,
    sign_bundle,
    verify_bundle,
)
from core.config import APTWatcherConfig, default_config, load_config
from core.integrations import (
    EnrichedTicket,
    GLPIResolverError,
    GLPITicketRefResolver,
    MCPSubprocessGLPIResolver,
    StubGLPIResolver,
)
from core.intel import (
    DEFAULT_VERDICT_PRECEDENCE,
    AptWatchProvider,
    HTTPIOCProviderBase,
    IOCAggregator,
    IOCProvider,
    IOCProviderError,
    IOCQuery,
    IOCTimeoutError,
    IOCTransportError,
    IOCUnsupportedError,
    StubIOCProvider,
    aggregate_results,
    build_aggregator,
    search_threatfox,
    search_tweetfeed,
)
from core.knowledge import KBLoadError, KnowledgeBase
from core.llm import (
    FakeClientExhausted,
    FakeModelClient,
    ModelClient,
    ModelMessage,
    ModelRequest,
    ModelResponse,
    PromptNotFoundError,
    load_prompt,
)
from core.llm_anthropic import (
    AnthropicAdapterError,
    AnthropicAPIError,
    AnthropicAuthError,
    AnthropicModelClient,
    AnthropicRateLimitError,
    AnthropicTransportError,
)
from core.preflight import build_evidence_manifest, preflight, probe_tool
from core.profiles import ALL_PROFILES, get_profile
from core.publish import (
    GLPIAttachmentAdapter,
    MispAdapter,
    NetcraftAdapter,
    PublicationAdapter,
    PublicationError,
    PublicationResult,
    StubPublicationAdapter,
)
from core.sift import (
    BULK_EXTRACTOR_SCANNERS,
    CHAINSAW_OUTPUT_FORMATS,
    CHAINSAW_SUBCOMMANDS,
    HAYABUSA_OUTPUT_FORMATS,
    PLASO_PARSER_PRESETS,
    REGRIPPER_PLUGINS,
    REGRIPPER_PROFILES,
    SIFT_UPDATE_PACKAGES,
    TIMESKETCH_QUERY_SUBCOMMANDS,
    TIMESKETCH_UPLOAD_CONSENT_TOKEN,
    VOLATILITY_PLUGINS,
    BulkExtractorScannerError,
    ChainsawOutputFormatError,
    ChainsawSearchError,
    ChainsawSubcommandError,
    HayabusaSubcommandError,
    PlasoOutputFormatError,
    PlasoParserPresetError,
    RegRipperPluginError,
    RegRipperProfileError,
    SiftUpdateConsentError,
    SiftUpdatePackageError,
    TimesketchHostError,
    TimesketchQueryError,
    TimesketchSubcommandError,
    TimesketchTimelineNameError,
    TimesketchUploadConsentError,
    ToolRunError,
    ToolRunResult,
    VolatilityPluginError,
    YaraScanError,
    parse_yara_output,
    run_bulk_extractor,
    run_chainsaw_hunt,
    run_chainsaw_search,
    run_fls,
    run_fsstat,
    run_hayabusa_logon_summary,
    run_hayabusa_timeline,
    run_icat,
    run_log2timeline,
    run_mmls,
    run_psort,
    run_regripper_plugin,
    run_regripper_profile,
    run_sift_update,
    run_timesketch_query,
    run_timesketch_upload,
    run_tool,
    run_volatility,
    run_yara_scan,
)
from core.strategies import (
    ALLOWED_SEVERITIES,
    LLMPlanner,
    LLMSelfCorrector,
    LLMVerifier,
    PlannerResponseError,
    SelfCorrectorResponseError,
    VerifierResponseError,
)
from core.types import (
    AuditEvent,
    ContainmentResult,
    EvidenceFile,
    Finding,
    FindingCitation,
    HostEvidence,
    IncidentRef,
    IOCAttribution,
    IOCProviderResult,
    IOCType,
    IOCVerdict,
    KBEntry,
    PreflightReport,
    ProfileDefinition,
    SourceType,
    SpoliationRisk,
    TicketRef,
    Tier,
    ToolVersion,
    Verdict,
    utcnow,
)

__all__ = [
    "ALLOWED_SEVERITIES",
    "ALL_PROFILES",
    "APTWatcherConfig",
    "AgentLoop",
    "AgentState",
    "AnthropicAPIError",
    "AnthropicAdapterError",
    "AnthropicAuthError",
    "AnthropicModelClient",
    "AnthropicRateLimitError",
    "AnthropicTransportError",
    "AuditEvent",
    "AuditLogger",
    "BULK_EXTRACTOR_SCANNERS",
    "BulkExtractorScannerError",
    "BundleManifest",
    "BundleSignatureError",
    "CHAINSAW_OUTPUT_FORMATS",
    "CHAINSAW_SUBCOMMANDS",
    "ChainsawOutputFormatError",
    "ChainsawSearchError",
    "ChainsawSubcommandError",
    "ContainmentResult",
    "DEFAULT_VERDICT_PRECEDENCE",
    "EnrichedTicket",
    "EvidenceFile",
    "ExecutionRecord",
    "FakeClientExhausted",
    "FakeModelClient",
    "Finding",
    "FindingCitation",
    "GLPIResolverError",
    "GLPITicketRefResolver",
    "HAYABUSA_OUTPUT_FORMATS",
    "AptWatchProvider",
    "HTTPIOCProviderBase",
    "HayabusaSubcommandError",
    "HostEvidence",
    "IOCAggregator",
    "IOCAttribution",
    "IOCProvider",
    "IOCProviderError",
    "IOCProviderResult",
    "IOCQuery",
    "IOCTimeoutError",
    "IOCTransportError",
    "IOCType",
    "IOCUnsupportedError",
    "IOCVerdict",
    "IncidentBundle",
    "IncidentRef",
    "KBEntry",
    "KBLoadError",
    "KnowledgeBase",
    "LLMPlanner",
    "LLMSelfCorrector",
    "LLMVerifier",
    "MCPSubprocessGLPIResolver",
    "ModelClient",
    "ModelMessage",
    "ModelRequest",
    "ModelResponse",
    "PLASO_PARSER_PRESETS",
    "PlanStep",
    "PlasoOutputFormatError",
    "PlasoParserPresetError",
    "PlannerResponseError",
    "PreflightReport",
    "ProfileDefinition",
    "PromptNotFoundError",
    "REGRIPPER_PLUGINS",
    "REGRIPPER_PROFILES",
    "RegRipperPluginError",
    "RegRipperProfileError",
    "ReportEmitError",
    "SIFT_UPDATE_PACKAGES",
    "SelfCorrectionDecision",
    "SelfCorrectorResponseError",
    "SiftUpdateConsentError",
    "SiftUpdatePackageError",
    "SourceType",
    "SpoliationRisk",
    "StubGLPIResolver",
    "StubIOCProvider",
    "TIMESKETCH_QUERY_SUBCOMMANDS",
    "TIMESKETCH_UPLOAD_CONSENT_TOKEN",
    "TicketRef",
    "Tier",
    "TimesketchHostError",
    "TimesketchQueryError",
    "TimesketchSubcommandError",
    "TimesketchTimelineNameError",
    "TimesketchUploadConsentError",
    "ToolRunError",
    "ToolRunResult",
    "ToolVersion",
    "VOLATILITY_PLUGINS",
    "Verdict",
    "VerificationIssue",
    "VerifierResponseError",
    "VolatilityPluginError",
    "YaraScanError",
    "__version__",
    "aggregate_results",
    "build_aggregator",
    "search_threatfox",
    "search_tweetfeed",
    "build_evidence_manifest",
    "default_config",
    "export_bundle",
    "generate_keypair",
    "get_profile",
    "import_bundle",
    "load_config",
    "load_prompt",
    "parse_yara_output",
    "preflight",
    "probe_tool",
    "run_bulk_extractor",
    "run_chainsaw_hunt",
    "run_chainsaw_search",
    "run_fls",
    "run_fsstat",
    "run_hayabusa_logon_summary",
    "run_hayabusa_timeline",
    "run_icat",
    "run_log2timeline",
    "run_mmls",
    "run_psort",
    "run_regripper_plugin",
    "run_regripper_profile",
    "run_sift_update",
    "run_timesketch_query",
    "run_timesketch_upload",
    "run_tool",
    "run_volatility",
    "run_yara_scan",
    "sign_bundle",
    "utcnow",
    "verify_bundle",
    # Phase 3.8 task #62 -- Rule generators.
    "RuleGenerationError",
    "SigmaRule",
    "SuricataRule",
    "YaraRule",
    "generate_sigma_rules",
    "generate_suricata_rules",
    "generate_yara_rules",
    # Phase 3.8 task #64 -- IOC exporters.
    "IOCExportError",
    "export_community_yaml",
    "export_per_type_txt",
    "export_stix_bundle",
    # Phase 3.8 task #63 -- Report renderers.
    "ReportRenderError",
    "render_analyst_markdown",
    "render_docx_report",
    "render_generation_report",
    "render_ttp_assessment",
    # Phase 3.8 task #65 -- Publication adapters.
    "GLPIAttachmentAdapter",
    "MispAdapter",
    "NetcraftAdapter",
    "PublicationAdapter",
    "PublicationError",
    "PublicationResult",
    "StubPublicationAdapter",
]
